# Generated by Django 3.2.13 on 2022-07-03 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220703_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set as returned'), ('abc', '123'))},
        ),
    ]
