# Generated by Django 3.2.13 on 2022-07-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_borrower', 'Can see book borrower'))},
        ),
    ]
